from __future__ import annotations

from typing import Any, Protocol

from ospilot.core.config import AppConfig


class DesktopBackend(Protocol):
    name: str

    def stop(self) -> None: ...

    def configure_background_app(self) -> None: ...

    def create_global_shortcuts(self, parent: Any, open_chat: Any, open_voice: Any, stop: Any) -> Any: ...

    def get_active_context(self) -> dict[str, Any]: ...

    def capture_screenshot_current_mouse_monitor(self, config: AppConfig) -> dict[str, Any]: ...

    def get_frontmost_ui_elements(self, query: str = "", limit: int = 120) -> dict[str, Any]: ...

    def move_mouse(self, target: dict[str, Any], duration_ms: int | None = None) -> dict[str, Any]: ...

    def click(self, target: dict[str, Any] | None = None, double: bool = False) -> dict[str, Any]: ...

    def right_click(self, target: dict[str, Any] | None = None) -> dict[str, Any]: ...

    def press_hotkey(self, keys: list[str]) -> dict[str, Any]: ...

    def type_text(self, text: str) -> dict[str, Any]: ...

    def focus_app(self, pid: int) -> dict[str, Any]: ...

    def open_app(self, app_name: str) -> dict[str, Any]: ...

    def read_clipboard(self) -> dict[str, Any]: ...

    def write_clipboard(self, text: str) -> dict[str, Any]: ...
